services:
  - type: web
    name: psau-admission-system
    env: php
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: PHP_VERSION
        value: 8.1
      - key: COMPOSER_INSTALL_OPTIONS
        value: --no-dev --optimize-autoloader
    healthCheckPath: /public/index.php
    plan: free
