services:
  # Web Service
  - type: web
    name: psau-admission-system
    env: php
    plan: starter
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php -v
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: PHP_VERSION
        value: 8.2
      - key: APP_ENV
        value: production
      - key: DB_TYPE
        value: postgresql
      - key: DB_HOST
        fromDatabase:
          name: psau-admission-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: psau-admission-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: psau-admission-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: psau-admission-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: psau-admission-db
          property: port
      - key: FIREBASE_API_KEY
        value: AIzaSyB7HqxV971vmWiJiXnWdaFnMaFx1C1t6s8
      - key: FIREBASE_AUTH_DOMAIN
        value: psau-admission-system.firebaseapp.com
      - key: FIREBASE_PROJECT_ID
        value: psau-admission-system
      - key: FIREBASE_STORAGE_BUCKET
        value: psau-admission-system.appspot.com
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: "522448258958"
      - key: FIREBASE_APP_ID
        value: 1:522448258958:web:994b133a4f7b7f4c1b06df
      - key: FIREBASE_EMAIL_FUNCTION_URL
        value: https://sendemail-alsstt22ha-uc.a.run.app

  # Database Service
  - type: pserv
    name: psau-admission-db
    env: postgresql
    plan: starter
    disk:
      name: psau-admission-disk
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
